### ISSUE TITLE
Study Overview

### ISSUE THREAD

**Issue by holtetx** [KSG-IT/ksg-nett#170]
It would be a nice feature to let people see who studies what. Some kind of page where you can select field of study and get a list of people.

**Comment by alexaor** [comment]
I like this idea! Lots of different ways to go about it depending on the extent of complexity we want.

- A Charfield restricted with options in the User model, issue here is maintaining a complete list of all fields of study etc.
- A FK to a model with a name field denoting the field of study which has to be unique. More flexibility and should be easy to just add another instance whenever something is missing and then this list can grow in a more dynamic manner.
- A more complex model using a `through` model which contains meta-data regarding a User's occupational status. This model can contain meta-data to keep track of people who are still students, what year they are in etc. The problems with this is general overengineering in addition to the fact that either users have to keep their profiles up to date, or "Personal" has to maintain this data.

The latter in this suggestion list might not even be doable as I've envisioned here, my knowledge of `M2M.through` usage is fairly limited.

**Comment by alexaor** [comment]
Scratch the M2M, doesn't make sense for a user to have more than one current field of study. Although the third option can be an expansion of point 2 and still hold, ish.
