### ISSUE TITLE
Missing bio field in User model

### ISSUE THREAD

**Issue by trmdy** [KSG-IT/ksg-nett#31]
In our design of the profile page, there seems to be a small bio the user can write about him/herself. We are currently lacking this in the User model. Should we perhaps add a TextField `bio` or similar to the User model?

This is perhaps something you can add @alexaor, as you are already working on the User model somewhat?

**Comment by alexaor** [comment]
In the User model in the recently pushed branch there's a bio TextField implemented already

**Comment by trmdy** [comment]
This actually seem to be adressed in your latest branch, am I right @alexaor?

**Comment by trmdy** [comment]
Great. I will close this issue when we merge that.

**Comment by alexaor** [comment]
#35
