### ISSUE TITLE
Editing user info resets first and last name to empty strings

### ISSUE THREAD

**Issue by alexaor** [KSG-IT/ksg-nett#39]

**Comment by chdefrene** [comment]
Might this be related to the form POSTing the updated data? In this case, a fix is to include the unmodified data in the request as well

**Comment by trmdy** [comment]
You need to be a bit more specific. Editing the user info how? What are (all) the specific inputs? What is the expected result?

The [user form](https://github.com/KSG-IT/ksg-nett/blob/ca664a16e11857b4a83bbde48ecfb4ebe38cc670/users/forms/user_form.py) includes the `first_name` and `last_name` fields and hence will update these on every save. If they are cleared in the form, they will also be cleared in the database when the form is submitted.

Testing the update user view locally (which I suspect is what you are referring to?), the form behaves as expected with regards to the `first_name` and `last_name` inputs.

**Comment by trmdy** [comment]
Can this be closed?

**Comment by alexaor** [comment]
Seeing as its due to poor implementation and not really a bug I don't see why not.
