### ISSUE TITLE
Move dependency management to pipenv?

### ISSUE THREAD

**Issue by trmdy** [KSG-IT/ksg-nett#50]
There seems to be some traction behind the tool [pipenv](https://github.com/pypa/pipenv).
The tool seems to greatly simplify dependency management for python projects. 

Should we perhaps consider moving to using pipenv, and hence the new Pipfile/Pipfile.lock format?

**Comment by chdefrene** [comment]
I am in favor!

**Comment by alexaor** [comment]
Also in favor
