### ISSUE TITLE
The confirmed quotes shown in quotes_list is hardcoded

### ISSUE THREAD

**Issue by trmdy** [KSG-IT/ksg-nett#52]
The particular line performing the logic is 

```
    {% if quote.get_semester_of_quote == 'H18' %}
```

We can work around doing a check in the view, by filtering the correct quotes on the backend. For instance, by adding a custom manager for the Quote model, eg named `this_semester`, so we can filter 

```
Quote.this_semester.all()
```

This can of course also be solved by doing the filtering every location it is needed, e.g. in the quotes_list view.

**Comment by alexaor** [comment]
#56 implements custom manager in the Quote model, but probably has to be expanded further seeing as the current views will not support this way of handling quotes. As of now the function for listing views in quotes/views.py returns two lists in its context, pending and approved quotes regardless of the semester of their origin.
