### ISSUE TITLE
Coveralls not building

### ISSUE THREAD

**Issue by alexaor** [KSG-IT/ksg-nett#55]
Currently no pull requests manage to run the coveralls test. Last working build was run on the 4th of December and new PR are stuck on 'Expecting result' from the build.

Referencing https://github.com/lemurheavy/coveralls-public/issues/905 which seems to have had the same problem and could be a possible solution.

**Comment by trmdy** [comment]
Seems to be an issue with [coveralls](http://status.coveralls.io/), and not our configuration. The issue you are referring has a different case, as they recently renamed their repository.
