### ISSUE TITLE
A quote can be related to multiple people

### ISSUE THREAD

**Issue by trmdy** [KSG-IT/ksg-nett#77]
I suggest we change the foreign key `quoter` into a ManyToMany field `quoters`/`tagged`, as multiple people can be part of a quote.

**Comment by Plebbimon** [comment]
![bilde](https://user-images.githubusercontent.com/31571115/116818992-6984df80-ab6e-11eb-899d-604f128575e7.png)
![bilde](https://user-images.githubusercontent.com/31571115/116819009-7d304600-ab6e-11eb-8290-eb0f3e9a5ee9.png)
