### ISSUE TITLE
Python 3.7

### ISSUE THREAD

**Issue by chdefrene** [KSG-IT/ksg-nett#81]
Should we upgrade to version 3.7?

**Comment by holtetx** [comment]
Yes pls

**Comment by alexaor** [comment]
Are there any reasons as to why we shouldn't?

**Comment by trmdy** [comment]
What are the specific reasons we should? Are there any features of 3.7 we should have? Are there any libraries we use that do not support 3.6? Are there any popular OS' that ship with 3.7, or for which 3.6 is hard to install? 

For the latest question, I believe that Ubuntu LTS (18.04) ship with 3.6 as the default. But for OS X users the story might be different?

**Comment by chdefrene** [comment]
> What are the specific reasons we should? 

[Python 3.6 considered harmful](https://www.youtube.com/watch?v=H4BB9eGUEaE&t=62s)

Having said that, I have no (good) arguments as to why we *need* to upgrade right now. Both 3.6 and 3.7 are pretty stable, although 3.7 introduces new functionality that means there's a risk for hiccups.  `<torvalds>` Nevertheless, this project concerns a web server, not a rocket guidance system, so that's a risk I'm willing to take. `</torvalds>`

The reason I raised this issue is that the 3.7 series has been out and stable for almost a year, and we're likely to encounter this issue as more of our dependecies make the upgrade. Personally, I like to tinker with new upgrades sooner than later, which gives us the ability to have discussions like this.
